// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClickableController from "./clickable_controller.js"
application.register("clickable", ClickableController)

import ConfirmationController from "./confirmation_controller.js"
application.register("confirmation", ConfirmationController)

import ContentLoaderController from "./content_loader_controller.js"
application.register("content-loader", ContentLoaderController)

import CounterCharsController from "./counter_chars_controller.js"
application.register("counter-chars", CounterCharsController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)

import InfiniteScrollController from "./infinite_scroll_controller.js"
application.register("infinite-scroll", InfiniteScrollController)

import ListController from "./list_controller.js"
application.register("list", ListController)

import ListNewItemController from "./list_new_item_controller.js"
application.register("list-new-item", ListNewItemController)

import SelectedLinkController from "./selected_link_controller.js"
application.register("selected-link", SelectedLinkController)

import SingleUploadController from "./single_upload_controller.js"
application.register("single-upload", SingleUploadController)
